// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalks.Data;

#nullable disable

namespace NZWalks.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20260526162234_Seeding data for Region and Difficulty")]
    partial class SeedingdataforRegionandDifficulty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalks.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4cee7041-0184-4cf6-89c3-cb9807d81dff"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("01b66037-49ed-4425-91ed-8ba53a1c9960"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("810aeabe-33fe-4cc6-8a90-6fe81240b8a2"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalks.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("32940b4e-3e60-448b-8d6f-177ce640542d"),
                            Code = "AKL",
                            Name = "Auckland",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Auckland_skyline_from_Mt_Eden.jpg/2560px-Auckland_skyline_from_Mt_Eden.jpg"
                        },
                        new
                        {
                            Id = new Guid("fd00093f-3493-445f-bd87-fb9b2ff1297b"),
                            Code = "WLG",
                            Name = "Wellington",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Wellington_City.jpg/2560px-Wellington_City.jpg"
                        },
                        new
                        {
                            Id = new Guid("8d7790f4-321a-4676-9445-d5145ac31f90"),
                            Code = "CAN",
                            Name = "Canterbury"
                        },
                        new
                        {
                            Id = new Guid("63273344-59d7-46b4-a85b-f9fbfbd0c78e"),
                            Code = "OTA",
                            Name = "Otago"
                        },
                        new
                        {
                            Id = new Guid("dd7ace6f-18ec-4b07-9248-1847786c04a2"),
                            Code = "BOP",
                            Name = "Bay of Plenty"
                        },
                        new
                        {
                            Id = new Guid("4c4b19d3-91ea-4994-94f4-abbda20a95d7"),
                            Code = "WAI",
                            Name = "Waikato",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Waikato_River.jpg/2560px-Waikato_River.jpg"
                        },
                        new
                        {
                            Id = new Guid("9939da5a-f9d2-4400-a7cb-0f222c6f46ac"),
                            Code = "TAR",
                            Name = "Taranaki",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Mt_Taranaki.jpg/2560px-Mt_Taranaki.jpg"
                        });
                });

            modelBuilder.Entity("NZWalks.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LengthInKm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NZWalks.Models.Domain.Walk", b =>
                {
                    b.HasOne("NZWalks.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalks.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
